//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public DichVu()
        {
            this.ChiTietDichVus = new HashSet<ChiTietDichVu>();
        }
    
        public int MaDV { get; set; }
        public string TenDV { get; set; }
        public Nullable<int> GiaDV { get; set; }
    
        public virtual ICollection<ChiTietDichVu> ChiTietDichVus { get; set; }
    }
}
