//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.ChiTietDichVus = new HashSet<ChiTietDichVu>();
            this.DangKyPhongs = new HashSet<DangKyPhong>();
        }
    
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> GiaPhong { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string DienTich { get; set; }
    
        public virtual ICollection<ChiTietDichVu> ChiTietDichVus { get; set; }
        public virtual ICollection<DangKyPhong> DangKyPhongs { get; set; }
    }
}
