//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDichVu
    {
        public int MaPhong { get; set; }
        public int MaDV { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<int> GiaPhong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string NgayBD { get; set; }
        public string NgayKT { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
