//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DangKyPhongs = new HashSet<DangKyPhong>();
        }
       
        public int MaKH { get; set; }
     
        public string TenKH { get; set; }
     
        public string Diachi { get; set; }
       
        public string SDT { get; set; }
     
        public string Nghenghiep { get; set; }
     
        public string CMND { get; set; }
    
        public virtual ICollection<DangKyPhong> DangKyPhongs { get; set; }
    }
}
