//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        
        public int UserID { get; set; }

        [Display(Name = "Tên đăng nhập")]
        [Required(ErrorMessage = "{0} không được để trống")]

        public string Username { get; set; }

        [Display(Name = "Mật Khẩu")]
        [Required(ErrorMessage = "{0} không được để trống")]
        [StringLength(50,ErrorMessage ="Mật khẩu phải có ít nhất 8 kí tự",MinimumLength =8)]
        public string Password { get; set; }

        [Display(Name = "Họ và Tên")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string Fullname { get; set; }
    }
}
